spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/secretshoprealm
          jwk-set-uri: http://localhost:8180/realms/secretshoprealm/protocol/openid-connect/certs