server.port=8380
spring.application.name=questMenu

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=questMenuGroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.template.default-topic=quest-requests
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.secretShop.questMenu.DTO.QuestRequest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=1000ms
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3