spring.application.name=keycloak
#keycloak.jwk-set-uri=http://localhost:8180/realms/secretshoprealm/protocol/openid-connect/certs
#keycloak.client-id=myclient
#keycloak.auth-server-url=http://localhost:8180
#keycloak.realm=secretshoprealm
#keycloak.client-secret=23NQ767KhjXbg9UuW4n4HlQKev3wBCjy

logging.level.org.springframework.security=DEBUG
logging.level.com.secretshop.keycloak=DEBUG

