spring.application.name=keycloak
keycloak.jwk-set-uri=http://localhost:8180/realms/secretshoprealm/protocol/openid-connect/certs
keycloak.client-id=myclient
keycloak.auth-server-url=http://localhost:8180
keycloak.realm=secretshoprealm
keycloak.client-secret=GwRxoWbFcrT1SwkGoWaN62KvBEGyfjmy